### PR TITLE
impl issue #37

### PR DESCRIPTION
**Pull request by jrmerz**
Let me know if you have questions.  Tested locally with `CLIENT_DEV=prod` flag.  New container based dist build seemed to be working.

### CODE REVIEW

**Review by qjhart — APPROVED** [review]
Looks great to me.  Under CLIENT_DEV=dev, nothing changes correct ? That is you need to run `npm run watch`

**Comment by jrmerz** [comment]
@qjhart correct

**Comment by qjhart** [comment]
One additional question.  Will dev and main branches auto push new images to dockerhub on commits?

**Comment by jrmerz** [comment]
That is separate from these changes.  But to answer it, only sandbox is set to auto deploy to the UCD server at the moment.

**Pull request merged**
